name: Build and Upload Flutter App

on:
  push:
    branches:
      - master
    tags:
      - 'release/*'

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'  

      - name: Install dependencies
        run: flutter pub get

      - name: Copy app_config.json
        run: cp app_config.json ./assets/app_config.json

      - name: Build Flutter App
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: flutter-app
          path: build/app/outputs/flutter-apk/app-release.apk