name: Build and upload Android app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and package Android app
        run: ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Android app
          path: app/build/outputs/apk/release/app-release.apk