name: Build and Upload Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build and package Android app
      run: |
        ./gradlew assembleRelease

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Android App
        path: app/build/outputs/apk/release/app-release.apk